service: serverless-url-shortener

provider:
  name: aws
  endpointType: ${file(config.json):API_ENDPOINT_TYPE}
  runtime: nodejs8.10
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):BUCKET}/*"

functions:
  store:
    handler: api/store.handle
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    ServerlesslyRedirectS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(config.json):BUCKET}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
    ServerlesslyRedirectS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${file(config.json):BUCKET}
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Resource:
                - arn:${file(config.json):S3_PARTITION}:s3:::${file(config.json):BUCKET}/*
              Principal: "*"
    ServerlesslyCloudfront:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Aliases:
            - s.cedar.ai
            - s.cedarai.com
          Origins:
            - Id: !Sub "S3-url-shortener"
              DomainName: !GetAtt ServerlesslyRedirectS3Bucket.WebsiteURL
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: !Sub "S3-url-shortener"
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: "none"
              Headers:
                - "Access-Control-Request-Headers"
                - "Access-Control-Request-Method"
                - "Origin"
            ViewerProtocolPolicy: "redirect-to-https"
            MinTTL: 0
            AllowedMethods:
              - "HEAD"
              - "GET"
            CachedMethods:
              - "HEAD"
              - "GET"
            SmoothStreaming: false
            DefaultTTL: 86400
            MaxTTL: 31536000
            Compress: false
          Enabled: true
          PriceClass: "PriceClass_100"
          ViewerCertificate:
            AcmCertificateArn: "arn:aws:acm:us-east-1:580226297183:certificate/c62c699d-9c22-41ae-b50e-500dd4512024"
            SslSupportMethod: "sni-only"
            MinimumProtocolVersion: "TLSv1.1_2016"
          HttpVersion: "http2"
          IPV6Enabled: true
    ServerlesslyRecordset1:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: !GetAtt ServerlesslyCloudfront.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: "Z2FDTNDATAQYW2"
        HostedZoneName: "cedar.ai."
        Name: s.cedar.ai
        Type: A
    ServerlesslyRecordset2:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: !GetAtt ServerlesslyCloudfront.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: "Z2FDTNDATAQYW2"
        HostedZoneName: "cedarai.com."
        Name: s.cedarai.com
        Type: A
